### ISSUE TITLE
Instructions for using this with static IP block

### ISSUE THREAD

**Issue by fx-byte** [owenthewizard/opnatt#7]
Hi all, 

Is there any way to continue using this bypass method with a static IP block from ATT?

I'm not sure what interfaces would need to be created or what I would need to do in opnsense to make that work. 

Apparently, ATT recommends using the "cascaded router" feature on the RG and pointing it to the opnsense box. 

Since I have this bypass working (thanks for the great instructions!), I'd rather continue to use the bypass and get the static IPs working there.

Thanks!

**Comment by owenthewizard** [comment]
Sorry I somehow did not see this issue.

I had static IP setup at one point, let me see if I can find the doc...

**Comment by owenthewizard** [comment]
[This](https://github.com/MonkWho/pfatt/issues/28#issuecomment-693930493) should help, from MonkWho/pfatt#28. [Source](https://www.reddit.com/r/PFSENSE/comments/c08qyt/wan_static_ip_issues/er34dkb/)

**Comment by fx-byte** [comment]
Thank you! It worked!
